Tracker Service
locomotivemtl/charcoal-email pull request #7
Opened 2020-08-07 16:39 UTC by mducharme

Add tracking options to charcoal-email.

- A new Tracker service that can add a tracking pixel and rewrite links in message's html.
- New `Link` object 
- `LinkLog` and `OpenLog` objects
- "API" with 2 routes: `email/v1/open/{email.id}[.png]` and `email/v1/link/{linkId}`

2020-08-10 14:40 UTC, mcaskill requested changes

2020-08-10 14:40 UTC, mcaskill commented on src/Charcoal/Email/Services/Parser.php
> +        $regexp = '/(.+[\s]+)?(<)?(([\w\-\._\+]+)@((?:[\w\-_]+\.)+)([a-zA-Z]*))?(>)?/u';
Could you change this variable into a public class constant.

2020-08-10 14:40 UTC, mcaskill commented on src/Charcoal/Email/Services/Tracker.php
> +            return $this->baseUrl.'email/v1/link/'.$linkId;
This is broken on my end. For example:

Before:

```html
<a href="https://github.com/mcaskill">GitHub</a>
```

After:

```html
https://charcoal.test/email/v1/link/5f315a878c47f>GitHub</a>
```

---

Fixed:

```php
$linkId  = $this->createLink($emailLogId, $matches[1]);
$linkUrl = $this->baseUrl.'email/v1/link/'.$linkId;
return str_replace($matches[1], $linkUrl, $matches[0]);
```

2020-08-11 22:57 UTC, mducharme commented on src/Charcoal/Email/Services/Tracker.php
> +            return $this->baseUrl.'email/v1/link/'.$linkId;
Will fix + add test.

2020-08-12 12:30 UTC, merged